const items_list = [
    {
        id: '101',
        image: 'objects/1.png',
        company: 'boohooMAN',
        item_name: 'Printed Oversized co-Ords',
        original_price: 2721,
        current_price: 1633,
        discount_percentage: 40,
        return_period: 10,
        delivery_date: '15 Oct 2024',
    },
    {
        id: '102',
        image: 'objects/2.png',
        company: 'Calvin Klein',
        item_name: 'Boys Solid Black T-shirt',
        original_price: 699,
        current_price: 350,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2024',  
    },
    {
        id: '103',
        image: 'objects/3.png',
        company: 'Aldo',
        item_name: 'Men Comfort Insole Sneakers',
        original_price: 8999,
        current_price: 5400,
        discount_percentage: 40,
        return_period: 4,
        delivery_date: '17 Oct 2024',
    },
    {
        id: '104',
        image: 'objects/4.png',
        company: 'The Collective',
        item_name: 'Men Gray Double-Knit Jacket',
        original_price: 11500,
        current_price: 6900,
        discount_percentage: 40,
        return_period: 15,
        delivery_date: '19 Oct 2024',
    },
    {
        id: '105',
        image: 'objects/5.png',
        company: 'Nautica',
        item_name: 'Men White Printed Casual Shirt',
        original_price: 1598,
        current_price: 799,
        discount_percentage: 50,
        return_period: 15,
        delivery_date: '11 Oct 2024',
    },
    {
        id: '106',
        image: 'objects/6.png',
        company: 'Boohoo',
        item_name: 'Suede Block Heels',
        original_price: 2759,
        current_price: 1932,
        discount_percentage: 30,
        return_period: 9,
        delivery_date: '10 Oct 2024',
    },
    {
        id: '107',
        image: 'objects/7.png',
        company: 'Raymond',
        item_name: 'Cotton Blend Casuals',
        original_price: 599,
        current_price: 360,
        discount_percentage: 40,
        return_period: 9,
        delivery_date: '10 Nov 2024',
    },
    {
        id: '108',
        image: 'objects/8.png',
        company: 'Levis',
        item_name: 'Black Comfort T-shirt',
        original_price: 640,
        current_price: 640,
        discount_percentage: 0,
        return_period: 11,
        delivery_date: '9 Sep 2024',
    },
    {
        id: '109',
        image: 'objects/9.png',
        company: 'Woodland',
        item_name: 'Sneakers for Men(Camel)',
        original_price: 2599,
        current_price: 1819,
        discount_percentage: 30,
        return_period: 7,
        delivery_date: '4 Jun 2024',
    },
    {
        id: '110',
        image: 'objects/10.png',
        company: 'Allen Solly',
        item_name: 'Pointed Block Heel',
        original_price: 1399,
        current_price: 800,
        discount_percentage: 43,
        return_period: 8,
        delivery_date: '17 July 2024',
    },
    {
        id: '111',
        image: 'objects/11.png',
        company: 'Mango',
        item_name: 'Embellished Party Stiletto Heels',
        original_price: 4392,
        current_price: 1757,
        discount_percentage: 60,
        return_period: 3,
        delivery_date: '23 Aug 2024',
    },
    {
        id: '112',
        image: 'objects/12.png',
        company: 'Mango',
        item_name: 'Men Straight Fits',
        original_price: 2634,
        current_price: 1844,
        discount_percentage: 30,
        return_period: 13,
        delivery_date: '30 Oct 2024',
    },
];